### ISSUE TITLE
Enhancement: AutoLayout In Overlay View

### ISSUE THREAD

**Issue by jstart** [0xced/MPMoviePlayerController-XCDOverlayView#3]
This is definitely a complicated feature request, but I wanted to get your opinion on how to use layout constraints in the overlay view.  I have a slightly more complicated overlay and I would like it to respond to constraints and rotation events.  I'll show you a demo of what I currently have working:
http://quick.as/o04dS1Y7

You can see that adjusting when the playback duration scrubber appears messed up my layout slightly.  In addition, I can't add constraints because of the asynchronous nature of the overlay view.  I would imagine I could wait for some sort of notification or callback when the moviePlayer has appeared and the overlayView has been adjusted, and then add my constraints.  Do you have any preference or idea of how to build an API like this?  I would be happy to work on a Pull Request for it, I just wanted to get your opinion before starting.  Thanks for all the great work on this utility!

Essentially I am trying to recreate the functionality seen in iTunes U:
![img_0103](https://cloud.githubusercontent.com/assets/108218/5534974/077e4030-8a26-11e4-9c09-2cf6064527a9.PNG)

Screenshot of my WWDC Variable Playback Speed project:
![ios simulator screen shot dec 22 2014 9 55 19 pm](https://cloud.githubusercontent.com/assets/108218/5534952/3fe1e874-8a25-11e4-8f7a-5c510945d3b9.png)

**Comment by 0xced** [comment]
I’m not sure to understand your issue. Auto Layout inside the overlay view should work just fine (on iOS 8+ at least). Have a look at the demo project: both subviews (title label and copyright button) have constraints. The title is aligned at top and the copyright aligned at the bottom. They both respond fine to rotation and scrubbing.

If that’s not what you need, please provide a sample project reproducing your issue.

**Comment by jstart** [comment]
Well AutoLayout should work as early as iOS supported that feature right (iOS 6 and up)?
My issue is that if I add constraints after assigning the overlayView, because I get an error saying that the view is not in the view hierarchy.  

Sample Project here:
https://github.com/jstart/WWDC-2x

I also need a way to make sure a view does NOT respond to scrubbing changes.  You can see below that my speed scrubber gets pushed down when I don't want it to:
![ios simulator screen shot dec 26 2014 8 17 49 pm](https://cloud.githubusercontent.com/assets/108218/5560416/4e0b7540-8d3c-11e4-9884-ff19e0d18911.png)

**Comment by 0xced** [comment]
Is your issue solved?

**Comment by jstart** [comment]
Yes thank you!

**Comment by 0xced** [comment]
Do you think there is something in the documentation (header file and/or README) I could add or clarify about how to use the overlay view?
